### ISSUE TITLE
sparseml installation for yolov5

### ISSUE THREAD

**Issue by ianfinley89** [neuralmagic/docs#159]
Within the documentation for installing sparseml it states to pip install: 

- `sparseml`
- `sparseml[torch,torchvsion]`
- `sparseml[tf_keras]`
- ...
However, I don't think sparseml.yolov5.train will work without also installing `sparseml[yolov5]`

If I only install `sparseml[torch,torchvision]` then

```
!sparseml.yolov5.train \
  --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn \
  --recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned75_quant-none?recipe_type=transfer_learn \
  --recipe-args '{"num_epochs":50, "quantization_epochs":5}' \
  --data VisDrone.yaml \
  --save-period 10 \
  --resume \
  --patience 0 \
  --cfg yolov5s.yaml \
  --hyp hyps/hyp.finetune.yaml
```
  
Traceback (most recent call last):
  File "/usr/local/bin/sparseml.yolov5.train", line 5, in <module>
    from sparseml.yolov5.scripts import train
  File "/usr/local/lib/python3.10/dist-packages/sparseml/yolov5/__init__.py", line 31, in <module>
    raise ImportError("Please install sparseml[yolov5] to use this pathway")
ImportError: Please install sparseml[yolov5] to use this pathway

**Comment by bfineran** [comment]
Hi @ianfinley89 you are correct, the `[yolov5]` extra is required for running our yolov5 scripts - could you point us to where you found this documentation?

**Comment by ianfinley89** [comment]
Hello, so if you go to https://docs.neuralmagic.com/get-started/transfer-a-sparsified-model/cv-object-detection, it requests that you do a sparseml torchvision install.

![image](https://github.com/neuralmagic/docs/assets/11452404/22c5a869-3e67-4665-9028-0dcfbcb3c343)

But that page does not include the necessary yolov5 extension installation to actually perform sparseml.yolov5.train.

**Comment by jeanniefinks** [comment]
Hi @ianfinley89 
The content got merged, and we await the next Doc rebuild for the changes to take effect.
I will close out this thread, but feel free to reopen if needed. Thank you!

Regards, 
Jeannie // Neural Magic
